import { readFile, mkdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { getPackageRoot } from './paths.js';
import { detectAgents } from './install/detect.js';
import { atomicWrite } from './fsutil.js';

const CLAUDE_DIR = join(homedir(), '.claude');
const SETTINGS_PATH = join(CLAUDE_DIR, 'settings.json');
const HOOKS_DIR = join(CLAUDE_DIR, 'hooks');
const HOOK_FILENAME = 'starlog-pkg-check.js';
const HOOK_PATH = join(HOOKS_DIR, HOOK_FILENAME);
const STARLOG_MARKER = '<!-- starlog:init -->';
const STARLOG_END_MARKER = '<!-- starlog:end -->';

// Shared instruction text used by all agent configs
const STARLOG_INSTRUCTIONS = `ALWAYS consult the \`starlog_search\` MCP tool before recommending or installing libraries for: authentication, email, background-jobs, feature-flags, caching, realtime, or orm-database.

The tool returns ranked recommendations with integration effort, skip-when conditions, hosted alternatives, and DIY-vs-buy analysis. Prefer its recommendations over training-data recall.`;

// ── Settings helpers ────────────────────────────────────────────────────

type Settings = Record<string, unknown>;

async function readSettingsJson(): Promise<Settings> {
  try {
    const raw = await readFile(SETTINGS_PATH, 'utf8');
    return JSON.parse(raw);
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      return { mcpServers: {}, hooks: {} };
    }
    throw new Error(`Failed to parse ${SETTINGS_PATH}: ${(err as Error).message}`);
  }
}

async function writeSettingsJson(settings: Settings): Promise<void> {
  // Atomic: a crash mid-write must never truncate the user's shared
  // settings.json (which holds unrelated MCP servers, hooks, and permissions).
  await atomicWrite(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n');
}

// ── MCP server ──────────────────────────────────────────────────────────

async function configureMcpServer(): Promise<{ changed: boolean }> {
  const settings = await readSettingsJson();
  if (!settings.mcpServers || typeof settings.mcpServers !== 'object') {
    settings.mcpServers = {};
  }
  const servers = settings.mcpServers as Record<string, unknown>;

  const pkgRoot = getPackageRoot();
  const desired = {
    command: 'node',
    args: [join(pkgRoot, 'dist', 'mcp.js')],
    description: 'starlog: capability manifest search -- library recommendations, DIY-vs-buy analysis, hosted alternatives',
  };

  if (JSON.stringify(servers.starlog) === JSON.stringify(desired)) {
    return { changed: false };
  }

  servers.starlog = desired;
  await writeSettingsJson(settings);
  return { changed: true };
}

async function removeMcpServer(): Promise<{ changed: boolean }> {
  const settings = await readSettingsJson();
  const servers = settings.mcpServers as Record<string, unknown> | undefined;
  if (!servers || !('starlog' in servers)) return { changed: false };
  delete servers.starlog;
  await writeSettingsJson(settings);
  return { changed: true };
}

// ── Hook script ─────────────────────────────────────────────────────────

function generateHookScript(): string {
  return `#!/usr/bin/env node
// starlog-pkg-check.js — PostToolUse hook
// Generated by: starlog init
// Checks if an installed package has a Starlog manifest with relevant guidance.

const fs = require('fs');
const path = require('path');

// Atomic write: temp sibling + rename, so a crash can't truncate the queue.
function writeFileAtomic(p, data) {
  var tmp = p + '.' + process.pid + '.tmp';
  fs.writeFileSync(tmp, data);
  fs.renameSync(tmp, p);
}

let CORPUS_DIR;
try {
  CORPUS_DIR = require('path').join(
    require('path').dirname(require.resolve('@starlog/index/package.json')),
    'corpus-free'
  );
} catch {
  CORPUS_DIR = ${JSON.stringify(join(getPackageRoot(), 'corpus-free'))};
}

let input = '';
const stdinTimeout = setTimeout(() => process.exit(0), 3000);
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
  clearTimeout(stdinTimeout);
  try {
    const data = JSON.parse(input);
    const cmd = (data.tool_input && data.tool_input.command) || '';

    const patterns = [
      /(?:npm\\s+(?:install|i|add))\\s+(.+)/i,
      /(?:pnpm\\s+add)\\s+(.+)/i,
      /(?:yarn\\s+add)\\s+(.+)/i,
      /(?:pip\\s+install)\\s+(.+)/i,
    ];

    let pkgArgs = null;
    let ecosystem = 'npm';
    for (const pat of patterns) {
      const m = cmd.match(pat);
      if (m) {
        pkgArgs = m[1];
        ecosystem = pat.source.includes('pip') ? 'pypi' : 'npm';
        break;
      }
    }
    if (!pkgArgs) { process.exit(0); }

    var rawPkgs = pkgArgs.split(/\\s+/).filter(function(a) { return !a.startsWith('-'); });

    for (var i = 0; i < rawPkgs.length; i++) {
      var originalPkg = rawPkgs[i];
      var pkg = normalizeToManifestId(originalPkg);
      const manifestPath = findManifest(pkg) || findManifest(pkg.replace(/-/g, ''));
      if (manifestPath) {
        const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
        const skipItems = (manifest.skip_when || [])
          .map(s => '  - ' + s).join('\\n');
        const alts = (manifest.alternative_ids || []).slice(0, 3).join(', ');
        console.log(
          '[Starlog] Found manifest for "' + manifest.name + '".\\n' +
          'Skip when:\\n' + skipItems + '\\n' +
          (alts ? 'Alternatives: ' + alts + '\\n' : '') +
          'Run starlog_search for full analysis.'
        );
      } else {
        // Queue for batch generation (per D-02, D-03)
        try {
          var homedir = require('os').homedir();
          var globalQueueDir = path.join(homedir, '.starlog');
          var globalQueuePath = path.join(globalQueueDir, 'pending.json');
          var localQueueDir = path.join(data.cwd || process.cwd(), '.starlog');
          var localQueuePath = path.join(localQueueDir, 'pending.json');

          var entry = {
            package_name: originalPkg,
            manifest_id: pkg,
            ecosystem: ecosystem,
            detected_at: new Date().toISOString(),
            source_project: data.cwd || process.cwd(),
            install_command: cmd,
            status: 'pending'
          };

          // Read global queue, deduplicate by manifest_id (per D-11)
          var globalQueue = [];
          try {
            globalQueue = JSON.parse(fs.readFileSync(globalQueuePath, 'utf8'));
          } catch (e) { /* file doesn't exist yet */ }

          var alreadyQueued = globalQueue.some(function(e) { return e.manifest_id === pkg; });
          if (!alreadyQueued) {
            globalQueue.push(entry);
            fs.mkdirSync(globalQueueDir, { recursive: true });
            writeFileAtomic(globalQueuePath, JSON.stringify(globalQueue, null, 2) + '\\n');

            // Append to project-local log
            var localQueue = [];
            try { localQueue = JSON.parse(fs.readFileSync(localQueuePath, 'utf8')); } catch (e) { /* */ }
            localQueue.push(entry);
            fs.mkdirSync(localQueueDir, { recursive: true });
            writeFileAtomic(localQueuePath, JSON.stringify(localQueue, null, 2) + '\\n');
          }

          // Output structured JSON for Claude context (per research recommendation)
          var output = {
            hookSpecificOutput: {
              hookEventName: 'PostToolUse',
              additionalContext: '[Starlog] No manifest for "' + originalPkg + '" -- queued for generation. It will be added to the index automatically.'
            }
          };
          console.log(JSON.stringify(output));
        } catch (e) {
          // Never fail -- advisory only
        }
      }
    }
  } catch (e) {
    // Never fail — advisory only
  }
  process.exit(0);
});

function normalizeToManifestId(pkg) {
  return pkg.replace(/^@[^\\/]+\\//, '')
    .replace(/\\./g, '-')
    .toLowerCase();
}

function findManifest(id) {
  try {
    const categories = fs.readdirSync(CORPUS_DIR, { withFileTypes: true })
      .filter(e => e.isDirectory());
    for (const cat of categories) {
      const p = path.join(CORPUS_DIR, cat.name, id + '.json');
      if (fs.existsSync(p)) return p;
    }
  } catch (e) { /* ignore */ }
  return null;
}
`;
}

async function installHookScript(): Promise<{ changed: boolean }> {
  // Write the hook file
  await mkdir(HOOKS_DIR, { recursive: true });
  const desired = generateHookScript();

  let existing: string | null = null;
  try {
    existing = await readFile(HOOK_PATH, 'utf8');
  } catch { /* doesn't exist yet */ }

  const fileChanged = existing !== desired;
  if (fileChanged) {
    await atomicWrite(HOOK_PATH, desired);
  }

  // Add hook entry to settings.json
  const settings = await readSettingsJson();
  if (!settings.hooks || typeof settings.hooks !== 'object') {
    settings.hooks = {};
  }
  const hooks = settings.hooks as Record<string, unknown[]>;
  if (!Array.isArray(hooks.PostToolUse)) {
    hooks.PostToolUse = [];
  }

  const hookCommand = `node "${HOOK_PATH}"`;
  const alreadyRegistered = hooks.PostToolUse.some((entry: unknown) => {
    const e = entry as { hooks?: Array<{ command?: string }> };
    return e.hooks?.some(h => h.command?.includes(HOOK_FILENAME));
  });

  if (alreadyRegistered && !fileChanged) {
    return { changed: false };
  }

  if (!alreadyRegistered) {
    hooks.PostToolUse.push({
      matcher: 'Bash',
      hooks: [{
        type: 'command',
        command: hookCommand,
        timeout: 10,
      }],
    });
    await writeSettingsJson(settings);
  }

  return { changed: true };
}

async function removeHookScript(): Promise<{ changed: boolean }> {
  // Remove hook entry from settings.json
  const settings = await readSettingsJson();
  const hooks = settings.hooks as Record<string, unknown[]> | undefined;
  if (hooks && Array.isArray(hooks.PostToolUse)) {
    const before = hooks.PostToolUse.length;
    hooks.PostToolUse = hooks.PostToolUse.filter((entry: unknown) => {
      const e = entry as { hooks?: Array<{ command?: string }> };
      return !e.hooks?.some(h => h.command?.includes(HOOK_FILENAME));
    });
    if (hooks.PostToolUse.length < before) {
      await writeSettingsJson(settings);
    }
  }

  // Remove the hook file
  try {
    await unlink(HOOK_PATH);
  } catch { /* already gone */ }

  return { changed: true };
}

// ── Marked instruction sections (CLAUDE.md / Copilot / Codex) ───────────
//
// These three agent-config files share one format: the Starlog block is
// delimited by an explicit start marker AND end marker so it can be removed
// without disturbing anything the user wrote before or after it.

/** The Starlog block, wrapped in start/end markers. Leading + trailing \n so it
 *  appends cleanly and removes back to the file's original bytes. */
function buildMarkedSection(): string {
  return `\n${STARLOG_MARKER}\n## Starlog — Capability Search\n\n${STARLOG_INSTRUCTIONS}\n${STARLOG_END_MARKER}\n`;
}

/**
 * Locate the Starlog section within a file's content. Returns the byte range
 * [start, end) to remove/replace — `start` consumes the section's leading
 * newline so an edit returns the file to its pre-install bytes.
 *
 * `bounded` is true only when a real end marker delimits the section (the safe
 * case for in-place replacement). Legacy installs (start marker, no end marker)
 * report `bounded: false` and a best-effort range; callers must not blind-write
 * over those without a backup.
 */
function findSectionBounds(
  content: string,
): { start: number; end: number; bounded: boolean } | null {
  if (!content.includes(STARLOG_MARKER)) return null;

  const withNl = content.indexOf(`\n${STARLOG_MARKER}`);
  const start = withNl !== -1 ? withNl : content.indexOf(STARLOG_MARKER);

  const endIdx = content.indexOf(STARLOG_END_MARKER, start);
  if (endIdx !== -1) {
    let end = endIdx + STARLOG_END_MARKER.length;
    if (content[end] === '\n') end += 1;
    return { start, end, bounded: true };
  }

  // Legacy install (no end marker): stop at the next HTML comment if present,
  // else EOF. Best-effort only.
  const nextComment = content.indexOf('\n<!-- ', start + 1);
  return { start, end: nextComment !== -1 ? nextComment : content.length, bounded: false };
}

/**
 * Ensure the Starlog section is present and up to date.
 * - Absent: append it.
 * - Present and current: no-op.
 * - Present but drifted (instruction text changed): replace it in place, but
 *   only for sections delimited by an end marker (the safe case). Legacy
 *   sections without an end marker are left untouched to avoid clobbering
 *   user content — uninstall+reinstall migrates them.
 */
export async function upsertMarkedSection(target: string): Promise<{ changed: boolean }> {
  let content = '';
  try {
    content = await readFile(target, 'utf8');
  } catch { /* doesn't exist yet */ }

  const desired = buildMarkedSection();
  const bounds = findSectionBounds(content);

  if (!bounds) {
    const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
    await atomicWrite(target, content + separator + desired);
    return { changed: true };
  }

  const existing = content.substring(bounds.start, bounds.end);
  if (existing === desired) {
    return { changed: false };
  }

  // Drifted. Only refresh sections we can bound precisely with an end marker.
  if (!bounds.bounded) {
    return { changed: false };
  }

  const updated = content.substring(0, bounds.start) + desired + content.substring(bounds.end);
  await atomicWrite(target, updated);
  return { changed: true };
}

/** Remove the Starlog section, preserving any content the user added before or
 *  after it. Backs the file up to `<file>.bak` before the (destructive) edit. */
export async function removeMarkedSection(
  target: string,
): Promise<{ changed: boolean; backedUp: boolean }> {
  let content: string;
  try {
    content = await readFile(target, 'utf8');
  } catch {
    return { changed: false, backedUp: false };
  }

  const bounds = findSectionBounds(content);
  if (!bounds) {
    return { changed: false, backedUp: false };
  }

  const cleaned = content.substring(0, bounds.start) + content.substring(bounds.end);
  await atomicWrite(`${target}.bak`, content);
  await atomicWrite(target, cleaned);
  return { changed: true, backedUp: true };
}

// ── CLAUDE.md ───────────────────────────────────────────────────────────

function writeClaudeMd(projectDir: string): Promise<{ changed: boolean }> {
  return upsertMarkedSection(join(projectDir, 'CLAUDE.md'));
}

function removeClaudeMd(projectDir: string): Promise<{ changed: boolean; backedUp: boolean }> {
  return removeMarkedSection(join(projectDir, 'CLAUDE.md'));
}

// ── Cursor (.cursor/rules/starlog.mdc) ─────────────────────────────────

function buildCursorMdc(): string {
  return `---
description: Starlog capability search for library recommendations
alwaysApply: true
---

${STARLOG_INSTRUCTIONS}
`;
}

async function configureCursor(projectDir: string): Promise<{ changed: boolean }> {
  const rulesDir = join(projectDir, '.cursor', 'rules');
  const target = join(rulesDir, 'starlog.mdc');
  const desired = buildCursorMdc();

  let existing: string | null = null;
  try {
    existing = await readFile(target, 'utf8');
  } catch { /* doesn't exist yet */ }

  if (existing === desired) {
    return { changed: false };
  }

  await atomicWrite(target, desired);
  return { changed: true };
}

async function removeCursor(projectDir: string): Promise<{ changed: boolean }> {
  const target = join(projectDir, '.cursor', 'rules', 'starlog.mdc');
  try {
    await unlink(target);
    return { changed: true };
  } catch {
    return { changed: false };
  }
}

// ── VS Code Copilot (.github/copilot-instructions.md) ──────────────────

function configureCopilot(projectDir: string): Promise<{ changed: boolean }> {
  return upsertMarkedSection(join(projectDir, '.github', 'copilot-instructions.md'));
}

function removeCopilot(projectDir: string): Promise<{ changed: boolean; backedUp: boolean }> {
  return removeMarkedSection(join(projectDir, '.github', 'copilot-instructions.md'));
}

// ── Codex (AGENTS.md) ──────────────────────────────────────────────────

function configureCodex(projectDir: string): Promise<{ changed: boolean }> {
  return upsertMarkedSection(join(projectDir, 'AGENTS.md'));
}

function removeCodex(projectDir: string): Promise<{ changed: boolean; backedUp: boolean }> {
  return removeMarkedSection(join(projectDir, 'AGENTS.md'));
}

// ── Orchestrator ────────────────────────────────────────────────────────

interface InitOpts {
  project?: boolean;
  uninstall?: boolean;
  all?: boolean;
}

export async function runInit(opts: InitOpts): Promise<void> {
  const projectDir = process.cwd();

  if (opts.uninstall) {
    console.log('Starlog — removing integrations...\n');

    // Global (Claude Code)
    const mcp = await removeMcpServer();
    const hook = await removeHookScript();
    console.log(mcp.changed  ? '  [x] MCP server removed' : '  [=] MCP server was not configured');
    console.log(hook.changed ? '  [x] Hook removed' : '  [=] Hook was not installed');

    // Project-level
    const md = await removeClaudeMd(projectDir);
    const cursor = await removeCursor(projectDir);
    const copilot = await removeCopilot(projectDir);
    const codex = await removeCodex(projectDir);
    console.log(md.changed      ? '  [x] CLAUDE.md section removed' : '  [=] No CLAUDE.md section found');
    console.log(cursor.changed  ? '  [x] Cursor rule removed (.cursor/rules/starlog.mdc)' : '  [=] No Cursor rule found');
    console.log(copilot.changed ? '  [x] Copilot instructions removed (.github/copilot-instructions.md)' : '  [=] No Copilot instructions found');
    console.log(codex.changed   ? '  [x] Codex instructions removed (AGENTS.md)' : '  [=] No Codex instructions found');

    // Surface backups so the user knows a .bak sibling was written.
    for (const [label, res] of [['CLAUDE.md', md], ['.github/copilot-instructions.md', copilot], ['AGENTS.md', codex]] as const) {
      if (res.backedUp) console.log(`      [i] Backed up ${label} -> ${label}.bak`);
    }

    console.log('\nDone. Restart your AI coding agent for changes to take effect.');
    return;
  }

  console.log('Starlog init — configuring AI coding agent integrations...\n');

  // Global: Claude Code (MCP server + hook)
  console.log('  Claude Code (global):');
  const mcp = await configureMcpServer();
  console.log(mcp.changed
    ? '    [+] MCP server configured in ~/.claude/settings.json'
    : '    [=] MCP server already configured');

  const hook = await installHookScript();
  console.log(hook.changed
    ? '    [+] PostToolUse hook installed (~/.claude/hooks/starlog-pkg-check.js)'
    : '    [=] Hook already installed');

  // Project-level agents: configure only the ones detected in this
  // environment, unless --all is passed. Keeps init from littering a
  // Claude-only repo with Cursor/Copilot/Codex files.
  const detection = detectAgents({ projectDir });

  console.log('  Cursor (project):');
  let cursor = { changed: false };
  if (opts.all || detection.cursor.detected) {
    cursor = await configureCursor(projectDir);
    console.log(cursor.changed
      ? '    [+] Rule added (.cursor/rules/starlog.mdc)'
      : '    [=] Already configured');
  } else {
    console.log(`    [-] Skipped — ${detection.cursor.reason} (use --all to force)`);
  }

  console.log('  VS Code Copilot (project):');
  let copilot = { changed: false };
  if (opts.all || detection.copilot.detected) {
    copilot = await configureCopilot(projectDir);
    console.log(copilot.changed
      ? '    [+] Instructions added (.github/copilot-instructions.md)'
      : '    [=] Already configured');
  } else {
    console.log(`    [-] Skipped — ${detection.copilot.reason} (use --all to force)`);
  }

  console.log('  Codex (project):');
  let codex = { changed: false };
  if (opts.all || detection.codex.detected) {
    codex = await configureCodex(projectDir);
    console.log(codex.changed
      ? '    [+] Instructions added (AGENTS.md)'
      : '    [=] Already configured');
  } else {
    console.log(`    [-] Skipped — ${detection.codex.reason} (use --all to force)`);
  }

  // Optional: CLAUDE.md project instructions
  if (opts.project) {
    console.log('  CLAUDE.md (project):');
    const md = await writeClaudeMd(projectDir);
    console.log(md.changed
      ? '    [+] Starlog instructions added to CLAUDE.md'
      : '    [=] Already configured');
  }

  const anyChanged = mcp.changed || hook.changed || cursor.changed || copilot.changed || codex.changed;
  console.log(anyChanged
    ? '\nDone! Restart your AI coding agent for changes to take effect.'
    : '\nEverything was already configured. No changes made.');
}
